version: '3.8'
volumes:
  mongo_data_v1:
    driver: local

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: products-api
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data_v1:/data/db

  nestjs:
    image: node:18
    container_name: nestjs
    working_dir: /app
    ports:
      - "3001:3001"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      MONGO_DOCKER_URI: "mongodb://root:example@mongo:27017/products-api?authSource=admin"
    command: sh -c "npm install && npm run start:dev"
    depends_on:
      - mongo
